# Configure this Discovery Server
spring:
  profiles: aws

server:
  port: 8085   # HTTP (Tomcat) port

eureka:
  server: # nothing useful found for project yet

  instance:
    preferIpAddress: false
    leaseExpirationDurationInSeconds: 10 # indicates the time that eureka server waits since it received the last
                                        # heartbeat before it can remove this instance from its view

    # eureka.instance.appname=${spring.application.name}

  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    region: default
    serviceUrl:
          defaultZone: http://ec2-34-215-110-22.us-west-2.compute.amazonaws.com:8085/eureka/
    # Notice that the serviceUrl is pointing to the same host as the local instance.
