spring:
  data:
    mongodb:
      uri: mongodb://52.16.139.0:27017/cooldb

  application:
    name: profile-service

eureka:
    instance:
        prefer-ip-address: true # When the application registers with eureka,
                                # it will use its IP Address rather than its hostname.
        leaseRenewalIntervalInSeconds: 5   # How often client send heartbeats to Eureka server
    client:
        serviceUrl:
            # It is possible to configure service urls so that client uses closest zone of availability
            # Check for references: https://github.com/spring-cloud/spring-cloud-netflix/issues/1327
            # defaultZone: http://localhost:8080/eureka/ # address of an Eureka Server
            defaultZone: http://34.215.110.22:8085/eureka/

server:
  port: 8092