server:
  port: 8086 # Zuul will run on 8086

spring:
  application:
    name: gateway

eureka:
  instance:
    prefer-ip-address: false # When the application registers with eureka, it will use its IP Address rather than its hostname.
    leaseRenewalIntervalInSeconds: 5   # how often client send heartbeats to Eureka server
  client:
    #registerWithEureka: true # true by default
    #fetchRegistry: true # true by default
    serviceUrl:
      defaultZone: http://ec2-54-201-208-226.us-west-2.compute.amazonaws.com:8085/eureka/
      #defaultZone: http://localhost:8085/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  #ignored-services: '*'
  routes:
    demo:
      path: /demo/**
      serviceId: DEMOMICROSERVER
    reg:
      path: /reg/**
      serviceId: registration-service
    profile:
      path: /profile/**
      serviceId: profile-service
    email:
      path: /email/**
      serviceId: email-service
    auth:
      path: /auth/**
      serviceId: authentication-service
