server:
  port: 8081

spring:
  application:
    name: gateway

eureka:
  instance:
    prefer-ip-address: true # When the application registers with eureka, it will use its IP Address rather than its hostname.
    leaseRenewalIntervalInSeconds: 5   # how often client send heartbeats to Eureka server
  client:
    #registerWithEureka: true # default
    #fetchRegistry: true # default
    serviceUrl:
      defaultZone: http://34.215.110.22:8080/eureka/
      #defaultZone: http://localhost:8080/eureka/

zuul:
  #ignored-services: '*'
  routes:
    demo:
      path: /demo/**
      serviceId: DEMOMICROSERVER
    reg:
      path: /reg/**
      serviceId: registration-service
