server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://34.215.110.22:8080/eureka/


zuul:
  #ignored-services: '*'
  routes:
    demo:
      path: /demo/**
      serviceId: DEMOMICROSERVER
