eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://34.215.110.22:8080/eureka/
      #defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: demomicroserver

server:
  port: 8090